[build]
  # Clean install + production build
  command   = "npm ci && npm run build"
  publish   = "dist/anamolydetector"

[build.environment]
  # Force Netlify to use Node 16 (or your chosen major version)
  NODE_VERSION = "16"

